### PR TITLE
Resource Change: aws-sso-scim_group enable group update and external id

### PR DESCRIPTION
**Pull request by davidsonjon**
Update the aws-sso-scim_group resource to support updates and optionally external_id property for SCIM implementation.

### CODE REVIEW

**Comment by JanKoppe** [comment]
Hey @davidsonjon, nice that you pick up work on this! :tada: 

Just as a heads up: AWS recently expanded the IdentityStore API pretty well, which hopefully makes this Terraform provider obsolete in the long run. We're currently not planning to add any new features on our own, but if you do the work and it looks good I'm absolutely willing to merge it. I'll probably only look at this in January due to vacation stuff, so please don't worry if a reply here takes a while.

**Comment by davidsonjon** [comment]
@JanKoppe thanks for the very prompt response!

Do you have a link to the new IdentityStore API - from what I have seen it will not support external identity providers? Happy to put in the work if it fits our use case.

Our use case is basically to allow us to manage our external identity provider groups then use this provider (with the updates related to this PR) to do the initial SCIM provisioning (displayName and externalId) so we can do the assignments in one codebase/run.

No worries on timing, enjoy your time off! 😄

**Comment by JanKoppe** [comment]
Hi @davidsonjon,

sorry for the late reply - I did not forget about your PR. But it's the usual new year rush at work. ;) I will put the review on my schedule for next week.

I was talking about the changes for this API: https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_Operations.html In the past they indeed did not work with external Identity Providers, but with the API changes it seems also this restriction was lifted. At least in my tests the API endpoints now work fully even with an external Identity Provider attached.

At least for us there are still some user attributes missing (like the `Active` attribute), which means we cannot fully switch over anytime soon. So this provider will probably need to be kept alive for some time to come.

**Comment by davidsonjon** [comment]
@JanKoppe thanks for the update and the insight!

I was able to confirm that the updated API changes do support my use case described above of pre-provisioning an identity store group, though it does require some lifecycle arguments for our needs. 

Having said that, this resource is much more straightforward to manage and robust then leveraging [aws_identitystore_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_group).

This change still has merit (imo) and may be of use to those with more advanced use-cases than **aws_identitystore_group** currently provides but will leave you to review and see what you think!

**Comment by JanKoppe** [comment]
Hey @davidsonjon,

I finally found the time to have a look: Seems like a really nice change! I appreciate the cleanups on the datatypes in function signatures. :) Makes it much nicer.

Two things that I've noticed:

1) Needs a `go fmt`, but I guess it's a Draft still.
2) I'd love to see an additional test-case for the update/PatchOp on the group. This would make sure that the PatchOp is behaving correctly and we can e.g. update the external ID or group name without a recreate. Did you plan on adding something like this as well, or should I take over from that point?

**Comment by davidsonjon** [comment]
Hopefully this covers what you were thinking, let me know what other feedback you have!

**Comment by JanKoppe** [comment]
Hi,

looks good! Tests pass fine here and make sense.

My local `go fmt` is still showing a whitespace diff:
```
diff --git a/internal/provider/resource_group.go b/internal/provider/resource_group.go
index 35198dc..4f093b8 100644
--- a/internal/provider/resource_group.go
+++ b/internal/provider/resource_group.go
@@ -31,7 +31,7 @@ func resourceGroup() *schema.Resource {
                                Description: "External ID for the group. This cannot be changed after creation.",
                                Type:        schema.TypeString,
                                Optional:    true,
-                               ForceNew: true,
+                               ForceNew:    true,
                        },
                },
        }
@@ -103,7 +103,7 @@ func resourceGroupUpdate(ctx context.Context, d *schema.ResourceData, meta inter
                })
                return diags
        }
-
+
        group.DisplayName = d.Get("display_name").(string)
        group.ExternalID = d.Get("external_id").(string)

@@ -113,7 +113,7 @@ func resourceGroupUpdate(ctx context.Context, d *schema.ResourceData, meta inter
                        {
                                Operation: "replace",
                                Path:      "displayName",
-                               Value: group.DisplayName,
+                               Value:     group.DisplayName,
                        },
                },
        }
@@ -122,7 +122,7 @@ func resourceGroupUpdate(ctx context.Context, d *schema.ResourceData, meta inter
                opmsg.Operations = append(opmsg.Operations, Operation{
                        Operation: "replace",
                        Path:      "externalId",
-                       Value: group.ExternalID,
+                       Value:     group.ExternalID,
                })
        }
```

If you could do a final run of `go fmt` in the `internal/provider` directory I think this would be ready to merge.

Thank you so much for the work on this!

**Review by JanKoppe — COMMENTED** [review]
LGTM

**Pull request merged**
